### ISSUE TITLE
Error inserting JSON column

### ISSUE THREAD

**Issue by B87** [bytefish/PgBulkInsert#30]
HI!

First of all, thanks for this library it has been really useful for me!

I'm opening an issue because I'm getting in trouble when I try to insert a POJO which contains a JSON field/cloumn.

If I try to insert a field which contains the JSON string : "{\"customer_name\": \"John\"}" i get the following error : 

de.bytefish.pgbulkinsert.exceptions.BinaryWriteFailedException: java.io.IOException: Ending write to copy failed.
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:163)
	at de.bytefish.pgbulkinsert.PgBulkInsert.saveAll(PgBulkInsert.java:80)
	at com.gindumac.mis.normalization.core.sink.PostgresSink.bulkStore(PostgresSink.java:41)
	... 1 more
Caused by: java.io.IOException: Ending write to copy failed.
	at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:107)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:161)
	... 3 more
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input syntax for type json
  Detail: Token "" is invalid.
  Where: JSON data, line 1: ...
COPY test, line 1, column json
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1116)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:965)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:45)
	at org.postgresql.copy.PGCopyOutputStream.endCopy(PGCopyOutputStream.java:168)
	at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:105)
	... 6 more

However, if I change the previous String by a null the insert finishes successfully (And I can se a null value in my table)

I'm using PostgreSQL 9.6.6 on AWS RDS.
 
Do you have any clue of what the error cause might be?

Thanks!

**Comment by bytefish** [comment]
Thanks for the bug report! Actually I think it is related to this: https://dba.stackexchange.com/a/156383. Basically you need to Escape the JSON before writing it. I will see what's the simplest way in Java. I label it as not a Bug, because it is a requirement imposed by Postgres, but I leave it open and we find a workaround! 😎

**Comment by bytefish** [comment]
Thanks for trying it! 🤜🤛 I will write a unit test first and then try to fix it. Don't know for sure, if I manage to today. Please hold on! 😌

**Comment by bytefish** [comment]
@B87 Did you also create the column as a JSONB Column? Because the Mapping maps to a JSONB column: https://github.com/bytefish/PgBulkInsert/blob/master/PgBulkInsert/src/main/java/de/bytefish/pgbulkinsert/mapping/AbstractMapping.java#L178.

**Comment by B87** [comment]
Yep that's my problem.... I was creating the column as a json, jsonb is fine so I'm happy with it.

Thanks for your time and help!
