### ISSUE TITLE
my thread is blocked by execute the method of org.postgresql.core.v3.QueryExecutorImpl.execute()

### ISSUE THREAD

**Issue by tangyibo** [bytefish/PgBulkInsert#50]
Hello @bytefish 

I use PgBuldInsert in my project now!  and I find a problem like this :  my thread is blocked by execute the method of org.postgresql.core.v3.QueryExecutorImpl.execute() , and the stack trace shows that the thread is still awaiting unlock:

```
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007203adb90> (a org.postgresql.core.v3.QueryExecutorImpl)
	at java.lang.Object.wait(Object.java:502)
	at org.postgresql.core.v3.QueryExecutorImpl.waitOnLock(QueryExecutorImpl.java:193)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:274)
	- locked <0x00000007203adb90> (a org.postgresql.core.v3.QueryExecutorImpl)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
```

so, I think there is something wrong in my code ,and after many tests , I found that there is no place to release the resource handle of PGCopyOutputStream when exception happened in **consumer.accept(row)** , and when  modify it like following code,  I successfully handle the problem above.

```
public class SimpleRowWriter {

    public static class Table {

        private final String schema;
        private final String table;
        private final String[] columns;

        public Table(String table, String... columns) {
            this(null, table, columns);
        }

        public Table(String schema, String table, String... columns) {
            this.schema = schema;
            this.table = table;
            this.columns = columns;
        }

        public String getSchema() {
            return schema;
        }

        public String getTable() {
            return table;
        }

        public String[] getColumns() {
            return columns;
        }

        public String GetFullyQualifiedTableName(boolean usePostgresQuoting) {
            return PostgreSqlUtils.getFullyQualifiedTableName(schema, table, usePostgresQuoting);
        }
    }

    private final Table table;
    private final boolean usePostgresQuoting;
    private final PgBinaryWriter writer;
    private final ValueHandlerProvider provider;
    private final Map<String, Integer> lookup;
    private PGCopyOutputStream output;

    public SimpleRowWriter(Table table) {
        this(table, false);
    }

    public SimpleRowWriter(Table table, boolean usePostgresQuoting) {
        this.table = table;
        this.usePostgresQuoting = usePostgresQuoting;

        this.writer = new PgBinaryWriter();
        this.provider = new ValueHandlerProvider();
        this.lookup = new HashMap<>();

        for (int ordinal = 0; ordinal < table.columns.length; ordinal++) {
            lookup.put(table.columns[ordinal], ordinal);
        }
    }

    public void open(PGConnection connection) throws SQLException  {
        this.output=new PGCopyOutputStream(connection, getCopyCommand(table, usePostgresQuoting), 1);
        writer.open(this.output);
    }

    public synchronized void startRow(Consumer<SimpleRow> consumer) {

        writer.startRow(table.columns.length);

        SimpleRow row = new SimpleRow(provider, lookup);

		try {
			consumer.accept(row);

			row.writeRow(writer);
		} catch(Exception e) {
			// I think should execute the method of class PGCopyOutputStream function close() to release resource；
			// Otherwise, this will make thread shock forever in postgresql dirver.
			//
			try {
				this.output.close();
			} catch (Exception ex) {
			}
			
			throw e;
		}
    }

    public void close() throws SQLException  {
        writer.close();
    }

    private static String getCopyCommand(Table table, boolean usePostgresQuoting) {

        String commaSeparatedColumns = Arrays.stream(table.columns)
                .map(x -> usePostgresQuoting ? PostgreSqlUtils.quoteIdentifier(x) : x)
                .collect(Collectors.joining(", "));

        return String.format("COPY %1$s(%2$s) FROM STDIN BINARY",
                table.GetFullyQualifiedTableName(usePostgresQuoting),
                commaSeparatedColumns);
    }
}

```

Looking forward to your feedback!!! 多谢!

**Comment by bytefish** [comment]
Thanks for your detailed analysis! I will add better error handling and close the stream like you suggest, if an error occurs. Sorry for the problems it caused you! 😖

**Comment by tangyibo** [comment]
@bytefish Look forward for your new version! 💯  Thanks.

**Comment by bytefish** [comment]
Is it possible, that you test if the commit fixes the problem? I couldn't reproduce it right now.

**Comment by tangyibo** [comment]
thank you very much!
